#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding=0, rgba8) uniform writeonly image2D out_image;
layout(binding=0, rgba8) uniform readonly image2D in_image;
void main() {
    vec4 image_r = imageLoad(in_image, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y));
    imageStore(out_image, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), image_r);
}